source 'https://rubygems.org'

gem 'jekyll'
gem 'kramdown'
gem 'coderay'
gem 'rake'
gem 'thor'
gem 'activesupport'
gem 'stringex'
gem 'mini_magick'
gem 'jekyll-minimagick', :git => 'git://github.com/svendroid/jekyll-minimagick'
gem 'glynn'